apiVersion: v1
kind: Service
metadata:
  name: {{ include "jpetstore-chart.fullname" . }}
  labels:
    {{- include "jpetstore-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "jpetstore-chart.selectorLabels" . | nindent 4 }}
